apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-shared-secret
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET: Md2DcKtJIOAiWmkN3+VpZH6Eyu7fyZy03KB5hHyV5n4=

  AUTH_DB_USERNAME: auth
  AUTH_DB_PASSWORD: auth
  PRODUCT_DB_USERNAME: auth
  PRODUCT_DB_PASSWORD: auth
  INVENTORY_DB_USERNAME: auth
  INVENTORY_DB_PASSWORD: auth
  ORDER_DB_USERNAME: auth
  ORDER_DB_PASSWORD: auth

  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""

