apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# In production, pin versions
images:
  - name: nguyenle1002/auth-service
    newTag: v1.0.0
  - name: nguyenle1002/product-service
    newTag: v1.0.0
  - name: nguyenle1002/inventory-service
    newTag: v1.0.0
  - name: nguyenle1002/order-service
    newTag: v1.0.0
  - name: nguyenle1002/api-gateway
    newTag: v1.0.0

# In production, use IfNotPresent to avoid unnecessary pulls if image is immutable
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent

